### ISSUE TITLE
"ctrl+/" insert "//"  instead of "<!-- -->"

### ISSUE THREAD

**Issue by nicgravel** [andrejunges/vscode-handlebars#1]
When using with node Js, express et handlebars in Visual Code.
Adding comment to hbs files doesn't work as normal without this extension.
Should add  " "  but it add "//" instead

**Comment by andrejunges** [comment]
Hey @nicgravel, I don't know exactly how to do that, so if you do, a PR would be really appreciated.
Anyway Im gonna look deeper into that when I get some time.

**Comment by andrejunges** [comment]
Its fixed on v. 0.1.0
Sorry for the delay..

**Comment by davidpmccormick** [comment]
I thought the block comment syntax for handlebars should be `{{!-- --}}`? I don't think regular html comments prevent handlebars from rendering.

**Comment by andrejunges** [comment]
@davidpmccormick  you're right, I've just published v0.1.2 with this fix. Thanks

**Comment by davidpmccormick** [comment]
Nice – thanks!
