### ISSUE TITLE
Please add a *.tpl filetype 

### ISSUE THREAD

**Issue by BANG88** [andrejunges/vscode-handlebars#2]
https://github.com/andrejunges/vscode-handlebars/blob/master/syntaxes/handlebars.tmLanguage#L19

**Comment by andrejunges** [comment]
hey @bang88, you mean adding here https://github.com/andrejunges/vscode-handlebars/blob/master/package.json#L26?

**Comment by BANG88** [comment]
@andrejunges yes,we use tpl ext as our `handlebars` template

**Comment by andrejunges** [comment]
@bang88 have just published 0.1.1 - should be fixed there :+1:

**Comment by BANG88** [comment]
@andrejunges good job !
