### ISSUE TITLE
Rename plugin?

### ISSUE THREAD

**Issue by mike-north** [andrejunges/vscode-handlebars#3]
I wasted some time trying to figure out where the `paper-*` snippets were coming from so I could remove them from vscode.

If you could name your plugin in a way that indicates that this isn't just for pure handlebars, it might save other developers from having to go on similar searches.

**Comment by andrejunges** [comment]
I think I'm gonna remove those snippets from the extension. I don't think that was a good idea.

**Comment by andrejunges** [comment]
should be fixed now at `0.2.0`
