### ISSUE TITLE
Ctrl+/ in hbs files creates html comments

### ISSUE THREAD

**Issue by peterblunden-egrowcery** [andrejunges/vscode-handlebars#4]
Hitting ctrl+/ in an hbs edit window inserts html comments `<!-- etc -->` instead of handlebars ones `{{!-- etc --}}`

**Comment by andrejunges** [comment]
that's strange, it used to work. they must have changed something related to it.
I'll dig deeper when I get some time.
Thanks for reporting it.

**Comment by peterblunden-egrowcery** [comment]
Yeah it stopped working after a recent vscode update. Great plugin - keep up the good work ;)

**Comment by peterblunden-egrowcery** [comment]
Looks like vscode v1.7.2 has fixed this :)
